### ISSUE TITLE
NUIParse not compiling with XCode 11. 

### ISSUE THREAD

**Issue by thegoal** [tombenner/NUIParse#9]
I have added NUIParse via pods. After updating Xcode to 11.0, I am not able to compile the project. Error is attached image.

![Screenshot 2019-09-24 at 7 02 04 PM](https://user-images.githubusercontent.com/3140170/65518742-355f2c80-defe-11e9-87b1-1a9f2cc753bd.png)

I tried removing and re-adding pods but didn't work. If someone can guide that will be appreciated.

**Comment by IlyaBoryanScopeTech** [comment]
I fixed this issue adding a separate getter for the "name" variable. Details are in the my [commit](https://github.com/tombenner/NUIParse/pull/10/commits/5219e49ddc5248113f04e818b89aaca232ab5f38)

**Comment by thegoal** [comment]
Please update this in Pods too.
